### ISSUE TITLE
Run tests for every commit/pull request with Travis CI

### ISSUE THREAD

**Issue by fitzgen** [ibsh/libKeyFinder#11]
I can do some research to see what configuration will be required, but I think you will have to create an API token for travis and enable the hook in the repo, @ibsh.

Looking at https://github.com/travis-ci/travis-ci/issues/577 for inspiration.

**Comment by ibsh** [comment]
I will take a look as soon as I have the time @fitzgen, thanks. Relocating this week though.

**Comment by ganwell** [comment]
@ibsh I did another go at the travis integration. I use this setup in my libraries and know it works decent. #27
