### ISSUE TITLE
Is libKeyFinder Release 2.1 OK to use?

### ISSUE THREAD

**Issue by tigerite** [ibsh/libKeyFinder#15]
Hi

From http://www.ibrahimshaath.co.uk/keyfinder/

2015-05-30: I've taken KeyFinder 2 offline as it contains a common crash caused by some library code. 

Does this crash affect libKeyFinder 2.1 or just the Mac OS GUI app that uses libKeyFinder?

Thanks.

**Comment by ibsh** [comment]
Just the GUI. The lib is fine.
