### ISSUE TITLE
iterator boundary issue in AudioData::downsample

### ISSUE THREAD

**Issue by SonicZentropy** [ibsh/libKeyFinder#18]
Note: I'm building on Windows, which I know is unsupported, but I'm pretty sure this is a generic bug that probably just didn't make itself apparent in OSX because of the undefined nature of the result.

In AudioData::downsample (audiodata.cpp), if shortcut=true, std::advance is called to move the readAt iterator forward by 'factor'.  This works fine normally, but it can (and does) attempt to advance past the end of the readAt iterator range when being called from KeyFinder::finalChromagram while flushing the remainder buffer when the buffer has remaining samples less than the downsample factor it attempts to advance by.

It's entirely possible I'm just doing something wrong to cause the problem since I've only been playing with the code for a couple hours, but I can't see how!  I quick tested by removing the shortcut lines altogether and the code works fine that way

**Comment by ibsh** [comment]
Looks right, nice catch. Do you have time to push a fix? I'll get to it eventually if not.

**Comment by SonicZentropy** [comment]
Yeah I'd be happy to tonight!
