### ISSUE TITLE
LGPL license change

### ISSUE THREAD

**Issue by poelzi** [ibsh/libKeyFinder#36]
We are about to add libKeyFinder in mixxx as alternative [key detection algorithm](https://github.com/mixxxdj/mixxx/pull/2689).
Would it be possible to re-license libKeyFinder under LGPL 3 so it can be used in non GPL3 software as well ?

**Comment by Be-ing** [comment]
LGPL allows library use by proprietary software. I would discourage that, and I presume that was @ibsh's intention when choosing GPL. There is no problem changing Mixxx to GPL v3 because Mixxx is currently GPL v2 _or later_.

**Comment by ibsh** [comment]
What @Be-ing said.
